name: MarksAPI
description: Share the marks!
website: https://github.com/yueyinqiu/MarksBukkit/wiki

version: '2.01'
author: yueyinqiu5990
main: top.nololiyt.yueyinqiu.bukkitplugins.marksapi.plugin.Plugin